# Exercícios

## 1) Crie uma classe que irá modelar características geométricas de um círculo. Deverá implementar os métodos:
        -> Área 
        -> Perímetro
## Utilize atributos de classe e de instância apropriados. Crie um inicializador e métodos.
$area = \pi*r^2$

$perimetro = 2*\pi*r$

In [10]:
# resposta 1
# biblioteca math
import math
class Geometrica:
    def areaCirculo(self,raio):
        return math.pi * raio**2
    def perimetroCirculo(self,raio):
        return 2 * math.pi * raio
    
obj = Geometrica()
print(obj.areaCirculo(3))
print(obj.perimetroCirculo(3))

28.274333882308138
18.84955592153876


## 2) Crie uma classe chamada matemática que conterá duas classes: trigonométrica e algébrica. Defina dentro da classe trigonométrica as seguintes funções:
    -> seno
    -> cosseno
    -> tangente
## Defina dentro da classe algébrica as seguintes funções: 
    -> soma
    -> subtração
    -> multiplicação
    -> divisão
## Cada função deverá receber array e retornar array

In [39]:
# resposta 2
# usar as funções built-in do numpy
import numpy as np

class Matematica:
    class Trigonometrica:
        def seno(self, array):
            return np.sin(array)
        def cosseno(self, array):
            return np.cos(array)
        def tangente(self, array):
            return np.tan(array)
        
    class Algebrica:
        def soma(self, array):
            return np.add(array, array)
        def subtracao(self, array):
            return np.subtract(array, array)
        def multiplicacao(self, array):
            return np.multiply(array, array)
        def divisao(self, array):
            return np.divide(array, array)
            
m = Matematica()
print('Seno: ', m.Trigonometrica().seno(np.array([3,5,6])))
print('Cosseno: ', m.Trigonometrica().cosseno(np.array([3,5,6])))
print('Tangente: ', m.Trigonometrica().tangente(np.array([3,5,6])))

print('Soma: ', m.Algebrica().soma(np.array([3,5,6])))
print('Subtração: ', m.Algebrica().subtracao(np.array([3,5,6])))
print('Multiplicação: ', m.Algebrica().multiplicacao(np.array([3,5,6])))
print('Divisão: ', m.Algebrica().divisao(np.array([3,5,6])))
    

Seno:  [ 0.14112001 -0.95892427 -0.2794155 ]
Cosseno:  [-0.9899925   0.28366219  0.96017029]
Tangente:  [-0.14254654 -3.38051501 -0.29100619]
Soma:  [ 6 10 12]
Subtração:  [0 0 0]
Multiplicação:  [ 9 25 36]
Divisão:  [1. 1. 1.]


## 3) Dados 2 arrays, A e B, remova de A todo elemento pertencente a B

In [40]:
# resposta 3
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

print(np.setdiff1d(array1, array2))

[1 2 3]


## 4) Crie uma função que recebe um array, um inteiro n e um inteiro m e que retorne outro array contendo elementos que estão entre os valores n e m do array recebido pela função. 

In [4]:
# resposta 4
def funcSlice(array, n, m):
    return array[n+1:m]

print(funcSlice([9, 12, 23, 4, 5, 6, 77, 8], 2, 7))

[4, 5, 6, 77]


## 5) Escreva uma função que recebe um vetor e um inteiro. Compare cada elemento desse vetor com o número inteiro. Se o elemento do vetor for maior, retorne a diferença entre eles, caso contrário, retorne a soma.

In [20]:
# resposta 5
import numpy as np

def funcWhere(arr, inteiro):
    return np.where(arr > inteiro, arr - inteiro, arr + inteiro)

arr1 = np.random.randint(1,10,size=[1,10])
print(arr1)
print(funcWhere(arr1, 3))

[[1 4 8 1 9 1 1 3 9 2]]
[[4 1 5 4 6 4 4 6 6 5]]


## 6) Dada a seguinte matriz:
    -> [ 8,1,7
         4,3,9
         5,2,6]
## escreva uma função que retorne a matriz ordenada por um dos eixos. utilize a função built-in sorted para realizar a ordenação

In [29]:
# resposta 6
# função sort
def funcM(matriz):
    return np.sort(matriz)
    

m1 = np.array([[8,1,7], [4,3,9], [5,2,6]])
print(m1)

print(np.apply_along_axis(funcM, 1, arr=m1))
print(np.apply_along_axis(funcM, 0, arr=m1))

[[8 1 7]
 [4 3 9]
 [5 2 6]]
[[1 7 8]
 [3 4 9]
 [2 5 6]]
[[4 1 6]
 [5 2 7]
 [8 3 9]]
